FROM arm64v8/python:alpine3.19

LABEL maintainer="Xu@nCh3n"

ENV TZ=Asia/Shanghai LANG=zh_CN.UTF-8 PYTHONUNBUFFERED=1

EXPOSE 8000

RUN set -eux && \
        \
        apk --no-cache update && apk -U --no-cache add git && \
        \
        mkdir -p /usr/src/myapp/ && \
        git clone https://github.com/Ccccx159/Emby_Notifier.git /usr/src/myapp/ && \
        python3 -m pip install --no-cache-dir requests colorlog aiohttp -q; 

ENTRYPOINT ["python3"]
CMD ["/usr/src/myapp/main.py"]